#ifndef UTILS_TIPO_SENTENCIA
#define UTILS_TIPO_SENTENCIA

typedef enum {
  SENTENCIA_DEFF,
  SENTENCIA_DEFL,
  SENTENCIA_APPLY,
  SENTENCIA_SEARCH,
  SENTENCIA_NULA
} TipoSentencia;

#endif // UTILS_TIPO_SENTENCIA